language: node_js
node_js: 
  - "4.1"
services: mongodb
before_script:
  - npm install -g gulp
script: gulp

notifications:
  slack: cuponthetop:z2GNywU1vQo5C1A7ndEVaZIs

travis encrypt "cuponthetop:z2GNywU1vQo5C1A7ndEVaZIs" --add notifications.slack